# Menus Principales
menu.nombre.principal=Principal
menu.nombre.idioma=Idioma
menu.nombre.productos=Gestión Productos
menu.nombre.usuarios=Gestión Usuarios
menu.nombre.ventas=Ventas
menu.nombre.compras=Compras
menu.nombre.proveedores=Proveedores
menu.nombre.perfil=Perfil
menu.nombre.cliente=Cliente

# Items Menu - Principal
menuitem.nombre.dashboard=Principal

# Items Menu - Gestion Productos
menuitem.nombre.productos=Productos
menuitem.nombre.categorias=Categorías
menuitem.nombre.marcas=Marcas

# Items Menu - Gestion Usuarios
menuitem.nombre.admins=Administradores
menuitem.nombre.cajeros=Cajeros
menuitem.nombre.clientes=Clientes

# Items MenÃº - Ventas
menuitem.nombre.nueva.venta=Nueva Venta
menuitem.nombre.historial.ventas=Historial Ventas
menuitem.nombre.anular.venta=Anular Venta

# Items Menu - Compras
menuitem.nombre.nueva.compra=Nueva Compra
menuitem.nombre.historial.compras=Historial Compras

# Items Menu - Proveedores
menuitem.nombre.gestion.proveedores=Gestionar Proveedores

# Items Menu - Perfil
menuitem.nombre.mi.perfil=Mi Perfil
menuitem.nombre.mi.direccion=Mi Dirección
menuitem.nombre.salir=Salir

# Items Menu - Cliente
menuitem.nombre.catalogo=Catálogo
menuitem.nombre.mi.carrito=Mi Carrito
menuitem.nombre.mis.compras=Mis Compras

# Estilos CSS
estilo.defecto=Estilo por Defecto
estilo.oscuro=Estilo Oscuro
estilo.azul=Estilo Azul
estilo.verde=Estilo Verde
estilo.rosado=Estilo Rosado

# Idiomas
idioma.espanol=Español
idioma.ingles=Ingles
idioma.frances=Frances  

# Labels de sesiï¿½n
}sesion.label=Sesión: {0} ({1})